FROM node:{{ node_version }}-alpine as builder

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn install

COPY . /app/
RUN yarn build

FROM node:{{ node_version }}-alpine as runner

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

{% if use_doppler %}
# Install Doppler CLI
RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
	echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
	apk add doppler
{% endif %}

COPY --from=builder /app/ /app/

WORKDIR /app/

# Link binary name
RUN yarn link
RUN npm prune --production

{% if use_doppler %}
ENTRYPOINT [ "doppler", "run", "--", "./bin/run" ]
{% else %}
ENTRYPOINT [ "./bin/run" ]
{% endif %}
