FROM node:{{ node_version }}-alpine as builder

WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn install \
	&& yarn link \
	&& npm prune --production

FROM node:{{ node_version }}-alpine as runner

# Install Doppler CLI
RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
	echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
	apk add doppler

COPY --from=builder /app/ /app/

WORKDIR /app/

# Link binary name
RUN yarn link

ENTRYPOINT [ "doppler", "run", "--", "{{ binary_name }}" ]

