.PHONY: docker docker-shell run-docker db-backup

docker:
	DOCKER_BUILDKIT=1 docker build -t {{ docker_image_name }} .

docker-shell: docker
	docker run --rm --entrypoint sh -it {{ docker_image_name }} /bin/bash

docker-push:
	docker push {{ docker_image_name }}

docker-run: docker
	docker run --rm -it {{ docker_image_name }}

# Backup the database to backup.sql
db-backup:
	pg_dump $POSTGRES_URL --verbose --format=p --file backup.sql