vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - WakaTime.vscode-wakatime@18.1.0
    - streetsidesoftware.code-spell-checker
    - eamodio.gitlens
    - mushan.vscode-paste-image
    - lukashass.volar
    - wayou.vscode-todo-highlight
    - nicoespeon.abracadabra
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/nick-lvov-dev/vsextensions/typescript-explicit-types/0.0.9/vspackage
